# Stage 0, "build-stage", based on Node.js, to build and compile the frontend
FROM tiangolo/node-frontend:10 as build-stage
WORKDIR /app

# Install the necesary packages
COPY package*.json /app/
RUN npm install

# Set the correct environment files and build
COPY ./ /app/
RUN rm .env.production; mv .env.development .env.production
RUN npm run build

# Stage 1, based on Nginx, to have only the compiled app, ready for production with Nginx
FROM nginx:1.15
COPY --from=build-stage /app/build/ /usr/share/nginx/html

EXPOSE 80

COPY --from=build-stage /app/nginx.conf /etc/nginx/conf.d/default.conf