# Stage 0, "build-stage", based on Node.js, to build and compile the frontend
FROM tiangolo/node-frontend:10 as build-stage

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
COPY package-lock.json ./
COPY gsap-bonus.tgz ./
RUN npm install --silent
RUN npm install ./gsap-bonus.tgz

# Copy over all code
COPY ./ /app/

# Set the correct environment files and build
RUN rm .env.production; mv .env.development .env.production
RUN npm run build

# Stage 1, based on Nginx, to have only the compiled app, ready for production with Nginx
FROM nginx:1.15
COPY --from=build-stage /app/build/ /usr/share/nginx/html

EXPOSE 80

COPY --from=build-stage /app/nginx.conf /etc/nginx/conf.d/default.conf