version: "3"

services:

    backend:
        build: ./backend
        container_name: backend
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile.dev
        container_name: frontend
        links:
        - backend
        ports:
        - 8080:80
