name: Test

on:
  push:
    branches-ignore:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      backend-directory: ./backend
      python_version: 3.7.0

    steps:
    - uses: actions/checkout@v2

    # Test the backend
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
        source $HOME/.poetry/env
        poetry export -f requirements.txt --dev > requirements.txt
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      working-directory: ${{ env.backend-directory }}
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 .
      working-directory: ${{ env.backend-directory }}
    - name: Test with pytest
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      run: |
        pytest -s tests\
      working-directory: ${{ env.backend-directory }}
